Repository GoogleCloudPlatform/blueprints, pull requests merged in 2021-07, with the labels that each got.

#25 chore: add prow lint presub
  .prow.yaml
Labels: approved, lgtm, size/S

#27 fix: yaml lint exit code
  utils/lint.sh
Labels: approved, lgtm, size/XS

#29 fix: Add workaround for setting prefix on networking package
  catalog/networking/network/setters.yaml
  catalog/networking/network/subnet/setters.yaml
Labels: approved, lgtm, size/XS

#31 chore: disable lint status
  .prow.yaml
Labels: approved, lgtm, size/XS

#16 Add GKE package
  catalog/gke/Kptfile
  catalog/gke/README.md
  catalog/gke/cluster/Kptfile
  catalog/gke/cluster/README.md
  catalog/gke/cluster/cluster.yaml
  catalog/gke/cluster/container-api.yaml
  catalog/gke/nodepools/primary/Kptfile
  catalog/gke/nodepools/primary/README.md
  catalog/gke/nodepools/primary/node-iam.yaml
  catalog/gke/nodepools/primary/nodepool.yaml
  catalog/gke/subnet/Kptfile
  catalog/gke/subnet/README.md
  catalog/gke/subnet/subnet.yaml
Labels: approved, lgtm, size/XL

#30 fix: only specify immediate setters in subnet setters.yaml
  catalog/networking/network/subnet/setters.yaml
Labels: approved, lgtm, size/XS

#34 Change add-attribution.sh to auto-detect vars
  utils/add-attribution.sh
Labels: approved, lgtm, size/S

#33 Extract project/kcc-namespace package
  catalog/project/Kptfile
  catalog/project/README.md
  catalog/project/kcc-namespace/Kptfile
  catalog/project/kcc-namespace/README.md
  catalog/project/kcc-namespace/kcc-namespace-viewer.yaml
  catalog/project/kcc-namespace/kcc-project-owner.yaml
  catalog/project/kcc-namespace/kcc.yaml
  catalog/project/kcc-namespace/namespace.yaml
Labels: approved, lgtm, size/L

#35 Add attribution annotations to gke package
  catalog/gke/cluster/cluster.yaml
  catalog/gke/cluster/container-api.yaml
  catalog/gke/nodepools/primary/Kptfile
  catalog/gke/nodepools/primary/node-iam.yaml
  catalog/gke/nodepools/primary/nodepool.yaml
  catalog/gke/subnet/Kptfile
  catalog/gke/subnet/subnet.yaml
Labels: approved, lgtm, size/S

#38 fix: move policy-controller-validate to `validators`
  catalog/landing-zone/Kptfile
Labels: approved, lgtm, size/XS

#40 Upgrade GKE package to kpt v1
  catalog/gke/Kptfile
  catalog/gke/README.md
  catalog/gke/cluster/Kptfile
  catalog/gke/cluster/README.md
  catalog/gke/cluster/cluster.yaml
  catalog/gke/cluster/container-api.yaml
  catalog/gke/cluster/setters.yaml
  catalog/gke/nodepools/primary/Kptfile
  catalog/gke/nodepools/primary/README.md
  catalog/gke/nodepools/primary/node-iam.yaml
  catalog/gke/nodepools/primary/nodepool.yaml
  catalog/gke/nodepools/primary/setters.yaml
  catalog/gke/setters.yaml
  catalog/gke/subnet/Kptfile
  catalog/gke/subnet/README.md
  catalog/gke/subnet/setters.yaml
  catalog/gke/subnet/subnet.yaml
Labels: approved, size/XL

#41 fix: Additional updates to landing zone for kpt v1 compatibility
  catalog/gitops/hydration-trigger.yaml
  catalog/hierarchy/bu/hierarchy.yaml
  catalog/hierarchy/bu/setters.yaml
  catalog/hierarchy/env-bu/hierarchy.yaml
  catalog/hierarchy/env-bu/setters.yaml
  catalog/hierarchy/simple/hierarchy.yaml
  catalog/hierarchy/simple/setters.yaml
  catalog/hierarchy/team/hierarchy.yaml
  catalog/hierarchy/team/setters.yaml
  catalog/landing-zone/namespaces/logging.yaml
  catalog/landing-zone/setters.yaml
  catalog/log-export/org/bigquery-export/setters.yaml
  catalog/networking/network/setters.yaml
  catalog/project/setters.yaml
Labels: approved, size/M

#42 Add utils/list-setters.sh
  utils/kpt-list-setters.sh
Labels: approved, lgtm, size/M

#46 Extract configsync pkg from gitops pkg
  catalog/gitops/Kptfile
  catalog/gitops/cloudbuild-iam.yaml
  catalog/gitops/configsync/config-management.yaml
  catalog/gitops/configsync/configsync-iam.yaml
  catalog/gitops/configsync/setters.yaml
  catalog/gitops/hydration-trigger.yaml
  catalog/gitops/services.yaml
  catalog/gitops/setters.yaml
  catalog/gitops/source-repositories.yaml
Labels: approved, lgtm, size/L

#53 Switching from using IAMPolicyMember to IAMPartialPolicy
  catalog/project/kcc-namespace/kcc-project-owner.yaml
  catalog/project/kcc-namespace/kcc.yaml
Labels: approved, lgtm, size/S
