Repository GoogleCloudPlatform/blueprints, pull requests merged in 2021-11, with the labels that each got.

#86 chore: fix prow config for timeout
  .prow.yaml
Labels: size/XS, lgtm, approved

#85 fix: updates function name for remove-annotated-resources
  catalog/gitops/hydration-trigger.yaml
Labels: size/XS, approved

#83 feat: Initial version of ACM blueprint
  catalog/acm/Kptfile
  catalog/acm/README.md
  catalog/acm/config-mgmt-csr.yaml
  catalog/acm/config-mgmt-iam.yaml
  catalog/acm/feat-config-mgmt.yaml
  catalog/acm/membership.yaml
  catalog/acm/services.yaml
  catalog/acm/setters.yaml
Labels: approved, size/L

#88 fix: change serviceusage api deletion policy to abandon and fix the resource ref for CSR repo
  catalog/acm/config-mgmt-iam.yaml
  catalog/acm/services.yaml
Labels: size/XS, lgtm, approved
