Repository GoogleCloudPlatform/blueprints, pull requests merged in 2021-06, with the labels that each got.

#9 Update kpt 1.0 blueprints ns
  bucket/Kptfile
  bucket/bucket.yaml
  redis-bucket/Kptfile
  redis-bucket/bucket.yaml
  redis-bucket/redis.yaml
Labels: lgtm, size/S

#10 chore: Put blueprints into a subdirectory
  catalog/bucket/Kptfile
  catalog/bucket/README.md
  catalog/bucket/bucket.yaml
  catalog/redis-bucket/Kptfile
  catalog/redis-bucket/README.md
  catalog/redis-bucket/bucket.yaml
  catalog/redis-bucket/redis.yaml
Labels: lgtm, size/XS

#12 chore:add owners for gh and prow
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, size/S

#13 feat: Import GitOps blueprint
  catalog/csr-gitops/Kptfile
  catalog/csr-gitops/README.md
  catalog/csr-gitops/cloudbuild-iam.yaml
  catalog/csr-gitops/configsync/Kptfile
  catalog/csr-gitops/configsync/config-management.yaml
  catalog/csr-gitops/configsync/configsync-iam.yaml
  catalog/csr-gitops/hydration-trigger.yaml
  catalog/csr-gitops/services.yaml
  catalog/csr-gitops/source-repositories.yaml
Labels: approved, lgtm, size/L

#15 An empty blueprint
  catalog/empty/Kptfile
  catalog/empty/README.md
  catalog/empty/noop.yaml
Labels: approved, lgtm, size/S

#19 Upgrade networking bp from v1alpha2 to v1
  catalog/networking/dns/managedzone-forwarding/Kptfile
  catalog/networking/dns/managedzone-forwarding/setters.yaml
  catalog/networking/dns/managedzone-peering/Kptfile
  catalog/networking/dns/managedzone-peering/setters.yaml
  catalog/networking/dns/managedzone-private/Kptfile
  catalog/networking/dns/managedzone-private/setters.yaml
  catalog/networking/dns/policy/Kptfile
  catalog/networking/dns/policy/setters.yaml
  catalog/networking/dns/recordset/Kptfile
  catalog/networking/dns/recordset/setters.yaml
  catalog/networking/firewall/common-rules/Kptfile
  catalog/networking/firewall/common-rules/setters.yaml
  catalog/networking/network/Kptfile
  catalog/networking/network/setters.yaml
  catalog/networking/network/subnet/Kptfile
  catalog/networking/network/subnet/setters.yaml
  catalog/networking/network/vpc/Kptfile
  catalog/networking/network/vpc/setters.yaml
  catalog/networking/peering/Kptfile
  catalog/networking/peering/setters.yaml
  catalog/networking/routes/routes-igw/Kptfile
  catalog/networking/routes/routes-igw/setters.yaml
  catalog/networking/shared-vpc/Kptfile
  catalog/networking/shared-vpc/setters.yaml
  catalog/networking/svpc-service-project/Kptfile
  catalog/networking/svpc-service-project/setters.yaml
  catalog/networking/vpc-service-controls/access-policy/Kptfile
  catalog/networking/vpc-service-controls/access-policy/setters.yaml
  catalog/networking/vpc-service-controls/perimeter/Kptfile
  catalog/networking/vpc-service-controls/perimeter/setters.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#20 Upgrade remaining blueprints
  catalog/bucket/Kptfile
  catalog/bucket/setters.yaml
  catalog/gitops/setters.yaml
  catalog/hierarchy/bu/setters.yaml
  catalog/landing-zone/setters.yaml
  catalog/log-export/folder/bigquery-export/Kptfile
  catalog/log-export/folder/bigquery-export/setters.yaml
  catalog/log-export/folder/pubsub-export/Kptfile
  catalog/log-export/folder/pubsub-export/setters.yaml
  catalog/log-export/folder/storage-export/Kptfile
  catalog/log-export/folder/storage-export/setters.yaml
  catalog/log-export/org/bigquery-export/Kptfile
  catalog/log-export/org/bigquery-export/setters.yaml
  catalog/log-export/org/pubsub-export/Kptfile
  catalog/log-export/org/pubsub-export/setters.yaml
  catalog/log-export/org/storage-export/Kptfile
  catalog/log-export/org/storage-export/setters.yaml
  catalog/project/setters.yaml
  catalog/redis-bucket/Kptfile
  catalog/redis-bucket/setters.yaml
  catalog/spanner/Kptfile
  catalog/spanner/setters.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L
