Repository GoogleCloudPlatform/blueprints, pull requests merged in 2021-08, with the labels that each got.

#55 Update add-attribribution and add fix-attribution.sh
  utils/add-attribution.sh
  utils/fix-attribution.sh
Labels: approved, lgtm, size/L

#56 Add component-versions.sh
  utils/component-versions.sh
Labels: approved, lgtm, size/M

#57 fix: gitops hydration trigger
  catalog/gitops/hydration-trigger.yaml
Labels: approved, lgtm, size/XS

#59 chore: add blueprint release-please configs
  .github/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: lgtm, approved, size/M

#61 feat: adds ha vpn to the networking blueprint
  catalog/networking/network/README.md
  catalog/networking/network/setters.yaml
  catalog/networking/network/vpn.yaml
Labels: approved, size/L

#60 chore: update release-please bootstrap sha
  release-please-config.json
Labels: size/XS, lgtm, approved

#62 Switch to using IAMPartialPolicy instead of IAMPolicyMember
  catalog/gitops/README.md
  catalog/gitops/cloudbuild-iam.yaml
  catalog/gitops/configsync/README.md
  catalog/gitops/configsync/configsync-iam.yaml
  catalog/landing-zone/README.md
  catalog/landing-zone/iam.yaml
  catalog/landing-zone/namespaces/hierarchy.yaml
  catalog/landing-zone/namespaces/logging.yaml
  catalog/landing-zone/namespaces/networking.yaml
  catalog/landing-zone/namespaces/policies.yaml
  catalog/landing-zone/namespaces/projects.yaml
  catalog/log-export/org/bigquery-export/README.md
  catalog/log-export/org/bigquery-export/iam.yaml
  catalog/project/kcc-namespace/README.md
Labels: lgtm, approved, size/L

#63 fix: minor fixes in IAMPartialPolicy
  catalog/gitops/configsync/configsync-iam.yaml
  catalog/landing-zone/namespaces/networking.yaml
Labels: size/XS, lgtm, approved

#67 feat: add automaticIamGrantsForDefaultServiceAccounts org policy
  catalog/landing-zone/README.md
  catalog/landing-zone/policies/disable-iam-grants-default-sa.yaml
Labels: lgtm, approved, size/M
