Repository GoogleCloudPlatform/blueprints, pull requests merged in 2021-09, with the labels that each got.

#66 feat: add example and test for bucket blueprint
  .gitignore
  .prow.yaml
  Makefile
  examples/simple-bucket/Kptfile
  examples/simple-bucket/README.md
  examples/simple-bucket/bucket.yaml
  examples/simple-bucket/setters.yaml
  test/integration/go.mod
  test/integration/go.sum
  test/integration/simple-bucket/simple_bucket_test.go
  utils/testutils/create_all.sh
  utils/testutils/krmt.sh
  utils/testutils/krmt_helpers.sh
Labels: size/XXL, approved

#71 Add location to bucket.yaml
  catalog/bucket/bucket.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#72 build: enable release-please app to tag GitHub releases
  .github/release-please.yml
Labels: size/XS, lgtm, approved

#70 chore: add network blueprint example and test
  examples/simple-network/Kptfile
  examples/simple-network/README.md
  examples/simple-network/setters.yaml
  examples/simple-network/subnet/Kptfile
  examples/simple-network/subnet/README.md
  examples/simple-network/subnet/nat.yaml
  examples/simple-network/subnet/setters.yaml
  examples/simple-network/subnet/subnet.yaml
  examples/simple-network/vpc/Kptfile
  examples/simple-network/vpc/README.md
  examples/simple-network/vpc/services.yaml
  examples/simple-network/vpc/setters.yaml
  examples/simple-network/vpc/vpc.yaml
  examples/simple-network/vpn.yaml
  test/integration/go.mod
  test/integration/go.sum
  test/integration/simple-network/simple_network_test.go
Labels: approved, size/XL
