Repository GoogleCloudPlatform/blueprints, pull requests merged in 2021-12, with the labels that each got.

#90 feat: Add foundational IAM blueprint
  catalog/iam-foundation/Kptfile
  catalog/iam-foundation/README.md
  catalog/iam-foundation/devops.yaml
  catalog/iam-foundation/networking.yaml
  catalog/iam-foundation/org.yaml
  catalog/iam-foundation/security.yaml
  catalog/iam-foundation/setters.yaml
Labels: lgtm, approved, size/L

#91 fix: add release-please config for IAM blueprint
  .release-please-manifest.json
  catalog/iam-foundation/devops.yaml
  catalog/iam-foundation/networking.yaml
  catalog/iam-foundation/org.yaml
  catalog/iam-foundation/security.yaml
  release-please-config.json
Labels: lgtm, approved, size/M

#89 feat: Change cluster and node pool defaults
  .gitignore
  catalog/gke/Kptfile
  catalog/gke/README.md
  catalog/gke/cluster/README.md
  catalog/gke/cluster/cluster.yaml
  catalog/gke/cluster/container-api.yaml
  catalog/gke/cluster/setters.yaml
  catalog/gke/nodepools/primary/README.md
  catalog/gke/nodepools/primary/node-iam.yaml
  catalog/gke/nodepools/primary/nodepool.yaml
  catalog/gke/nodepools/primary/setters.yaml
  catalog/gke/setters.yaml
  catalog/gke/subnet/Kptfile
  catalog/gke/subnet/README.md
  catalog/gke/subnet/setters.yaml
  catalog/gke/subnet/subnet.yaml
Labels: approved, size/L

#92 fix: Clean up of setters and variables
  catalog/acm/README.md
  catalog/acm/config-mgmt-csr.yaml
  catalog/acm/config-mgmt-iam.yaml
  catalog/acm/feat-config-mgmt.yaml
  catalog/acm/membership.yaml
  catalog/acm/services.yaml
  catalog/acm/setters.yaml
Labels: approved, size/M

#112 chore: fix iam-foundation initial version
  .release-please-manifest.json
Labels: size/XS, lgtm, approved

#113 fix: add release-please config for ACM and Anthos Cluster blueprints
  .release-please-manifest.json
  release-please-config.json
Labels: size/S, approved

#115 fix: use setter defaults in ACM config
  catalog/acm/acm-membership-api.yaml
  catalog/acm/config-mgmt-csr.yaml
  catalog/acm/config-mgmt-iam.yaml
  catalog/acm/feat-config-mgmt.yaml
  catalog/acm/membership.yaml
  catalog/acm/services.yaml
Labels: lgtm, approved, size/M

#114 fix: update anthos-cluster blueprint sub packages
  catalog/anthos-cluster/acm/Kptfile
  catalog/anthos-cluster/acm/acm-membership-api.yaml
  catalog/anthos-cluster/gke/CHANGELOG.md
  catalog/anthos-cluster/gke/Kptfile
  catalog/anthos-cluster/gke/cluster/cluster.yaml
  catalog/anthos-cluster/gke/cluster/container-api.yaml
  catalog/anthos-cluster/gke/nodepools/primary/node-iam.yaml
  catalog/anthos-cluster/gke/nodepools/primary/nodepool.yaml
Labels: approved, size/M

#117 chore: explicit release as for acm and anthos-cluster
  release-please-config.json
Labels: size/XS, lgtm, approved

#118 chore: add lz-lite release configs
  .release-please-manifest.json
  release-please-config.json
Labels: size/XS, lgtm, approved

#120 fix: landing zone lite fmt
  catalog/landing-zone-lite/services.yaml
Labels: size/XS, lgtm, approved

#122 fix: add correct attribution for lz lite
  catalog/landing-zone-lite/iam.yaml
  catalog/landing-zone-lite/namespaces/hierarchy.yaml
  catalog/landing-zone-lite/namespaces/projects.yaml
  catalog/landing-zone-lite/services.yaml
Labels: lgtm, approved, size/M

#123 chore: remove bootstrap release-as
  release-please-config.json
Labels: size/XS, lgtm, approved

#125 chore: format meta resources
  catalog/acm/setters.yaml
  catalog/anthos-cluster/acm/setters.yaml
  catalog/anthos-cluster/gke/cluster/setters.yaml
  catalog/anthos-cluster/gke/nodepools/primary/setters.yaml
  catalog/anthos-cluster/gke/setters.yaml
  catalog/anthos-cluster/setters.yaml
  catalog/bucket/setters.yaml
  catalog/gke/cluster/setters.yaml
  catalog/gke/nodepools/primary/setters.yaml
  catalog/gke/setters.yaml
  catalog/hierarchy/bu/setters.yaml
  catalog/hierarchy/env-bu/setters.yaml
  catalog/hierarchy/simple/setters.yaml
  catalog/hierarchy/team/setters.yaml
  catalog/iam-foundation/setters.yaml
  catalog/landing-zone-lite/setters.yaml
  catalog/landing-zone/setters.yaml
  catalog/log-export/folder/bigquery-export/setters.yaml
  catalog/log-export/folder/pubsub-export/setters.yaml
  catalog/log-export/folder/storage-export/setters.yaml
  catalog/log-export/org/bigquery-export/setters.yaml
  catalog/log-export/org/pubsub-export/setters.yaml
  catalog/log-export/org/storage-export/setters.yaml
  catalog/networking/dns/managedzone-forwarding/setters.yaml
  catalog/networking/dns/managedzone-peering/setters.yaml
  catalog/networking/dns/managedzone-private/setters.yaml
  catalog/networking/dns/policy/setters.yaml
  catalog/networking/dns/recordset/setters.yaml
  catalog/networking/firewall/common-rules/Kptfile
  catalog/networking/firewall/common-rules/setters.yaml
  catalog/networking/network/Kptfile
  catalog/networking/network/setters.yaml
  catalog/networking/network/subnet/setters.yaml
  catalog/networking/network/vpc/setters.yaml
  catalog/networking/peering/setters.yaml
  catalog/networking/routes/routes-igw/setters.yaml
  catalog/networking/shared-vpc/setters.yaml
  catalog/networking/svpc-service-project/setters.yaml
  catalog/networking/vpc-service-controls/access-policy/setters.yaml
  catalog/networking/vpc-service-controls/perimeter/setters.yaml
  catalog/project/kcc-namespace/setters.yaml
  catalog/project/kcc-namespace/validation.yaml
  catalog/project/setters.yaml
  catalog/redis-bucket/setters.yaml
  catalog/spanner/setters.yaml
  utils/lint.sh
Labels: lgtm, approved, size/M
