Repository GoogleCloudPlatform/blueprints, pull requests merged in 2022-01, with the labels that each got.

#126 fix: bump kpt version in hydration pipeline
  catalog/gitops/hydration-trigger.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#129 feat: Add GKE Autopilot blueprint
  .release-please-manifest.json
  catalog/gke-autopilot/CHANGELOG.md
  catalog/gke-autopilot/Kptfile
  catalog/gke-autopilot/README.md
  catalog/gke-autopilot/cluster/Kptfile
  catalog/gke-autopilot/cluster/README.md
  catalog/gke-autopilot/cluster/cluster.yaml
  catalog/gke-autopilot/cluster/container-api.yaml
  catalog/gke-autopilot/cluster/setters.yaml
  catalog/gke-autopilot/setters.yaml
  release-please-config.json
Labels: lgtm, approved, size/L

#132 fix: remove redundant project annotation from IAMPartialPolicy
  catalog/project/kcc-namespace/kcc.yaml
Labels: size/XS, lgtm, approved

#128 chore: regenerate docs using docs kfn
  catalog/acm/README.md
  catalog/anthos-cluster/README.md
  catalog/bucket/README.md
  catalog/empty/README.md
  catalog/gitops/README.md
  catalog/gitops/configsync/README.md
  catalog/gke-autopilot/README.md
  catalog/gke/README.md
  catalog/gke/cluster/README.md
  catalog/gke/nodepools/primary/README.md
  catalog/hierarchy/bu/README.md
  catalog/hierarchy/env-bu/README.md
  catalog/hierarchy/simple/README.md
  catalog/hierarchy/team/README.md
  catalog/iam-foundation/README.md
  catalog/landing-zone-lite/README.md
  catalog/landing-zone/README.md
  catalog/log-export/folder/bigquery-export/README.md
  catalog/log-export/folder/pubsub-export/README.md
  catalog/log-export/folder/storage-export/README.md
  catalog/log-export/org/bigquery-export/README.md
  catalog/log-export/org/pubsub-export/README.md
  catalog/log-export/org/storage-export/README.md
  catalog/networking/dns/managedzone-forwarding/README.md
  catalog/networking/dns/managedzone-peering/README.md
  catalog/networking/dns/managedzone-private/README.md
  catalog/networking/dns/policy/README.md
  catalog/networking/dns/recordset/README.md
  catalog/networking/firewall/common-rules/README.md
  catalog/networking/network/README.md
  catalog/networking/network/subnet/README.md
  catalog/networking/network/vpc/README.md
  catalog/networking/peering/README.md
  catalog/networking/routes/routes-igw/README.md
  catalog/networking/shared-vpc/README.md
  catalog/networking/svpc-service-project/README.md
  catalog/networking/vpc-service-controls/access-policy/README.md
  catalog/networking/vpc-service-controls/perimeter/README.md
  catalog/project/README.md
  catalog/project/kcc-namespace/README.md
  catalog/redis-bucket/README.md
  catalog/spanner/README.md
  utils/fix-readmes.sh
Labels: size/XXL, approved

#137 chore: release version number for gke-autopilot blueprint
  .release-please-manifest.json
  release-please-config.json
Labels: size/XS, approved
