Repository GoogleCloudPlatform/blueprints, pull requests merged in 2022-02, with the labels that each got.

#141 fix: remove namespace setters from bucket and redis blueprints
  catalog/bucket/README.md
  catalog/bucket/bucket.yaml
  catalog/bucket/setters.yaml
  catalog/redis-bucket/README.md
  catalog/redis-bucket/bucket.yaml
  catalog/redis-bucket/redis.yaml
  catalog/redis-bucket/setters.yaml
Labels: size/S, approved

#147 fix: GKE autopilot attribution
  catalog/gke-autopilot/cluster/cluster.yaml
  catalog/gke-autopilot/cluster/container-api.yaml
Labels: size/XS, lgtm, approved

#148 fix: remove leftover references to platform-project-id
  catalog/acm/README.md
  catalog/acm/acm-membership-api.yaml
  catalog/anthos-cluster/README.md
  catalog/anthos-cluster/acm/acm-membership-api.yaml
Labels: approved, size/M

#149 chore: remove release-as config for gke-autopilot
  release-please-config.json
Labels: size/XS, approved

#146 chore: add readme check in CI
  .prow.yaml
  Makefile
  catalog/bucket/README.md
  catalog/redis-bucket/README.md
  utils/fix-readmes.sh
  utils/kpt-list-setters.sh
  utils/kpt-pkg-readme.sh
  utils/lint.sh
Labels: approved, size/XL

#151 Make bucket setter free.
  catalog/bucket/Kptfile
  catalog/bucket/bucket.yaml
  catalog/bucket/setters.yaml
Labels: approved, needs-ok-to-test, size/M

#158 fix: reduce setters for GKE blueprint
  catalog/gke/README.md
  catalog/gke/cluster/README.md
  catalog/gke/cluster/cluster.yaml
  catalog/gke/cluster/container-api.yaml
  catalog/gke/cluster/setters.yaml
  catalog/gke/nodepools/primary/README.md
  catalog/gke/nodepools/primary/node-iam.yaml
  catalog/gke/nodepools/primary/nodepool.yaml
  catalog/gke/nodepools/primary/setters.yaml
  catalog/gke/setters.yaml
Labels: lgtm, approved, size/M

#157 fix: reduce setters for ACM blueprint
  catalog/acm/README.md
  catalog/acm/acm-membership-api.yaml
  catalog/acm/config-mgmt-csr.yaml
  catalog/acm/config-mgmt-iam.yaml
  catalog/acm/feat-config-mgmt.yaml
  catalog/acm/membership.yaml
  catalog/acm/services.yaml
  catalog/acm/setters.yaml
Labels: lgtm, approved, size/L

#159 fix: reduce setters for GKE Autopilot blueprint
  catalog/gke-autopilot/README.md
  catalog/gke-autopilot/cluster/cluster.yaml
  catalog/gke-autopilot/cluster/container-api.yaml
  catalog/gke-autopilot/cluster/setters.yaml
  catalog/gke-autopilot/setters.yaml
Labels: size/S, lgtm, approved
