Repository GoogleCloudPlatform/blueprints, pull requests merged in 2022-05, with the labels that each got.

#183 chore: add IAMAuditConfig example
  examples/iam-audit-config/Kptfile
  examples/iam-audit-config/README.md
  examples/iam-audit-config/audit.yaml
  examples/iam-audit-config/setters.yaml
Labels: lgtm, approved, size/L

#186 fix: add missing project-ids to log-export resources
  catalog/log-export/folder/bigquery-export/README.md
  catalog/log-export/folder/bigquery-export/export.yaml
  catalog/log-export/folder/pubsub-export/README.md
  catalog/log-export/folder/pubsub-export/export.yaml
  catalog/log-export/folder/storage-export/README.md
  catalog/log-export/folder/storage-export/export.yaml
Labels: size/S, lgtm, approved

#185 fix: add setters for retention period in log bucket
  catalog/log-export/folder/storage-export/README.md
  catalog/log-export/folder/storage-export/export.yaml
  catalog/log-export/folder/storage-export/setters.yaml
  catalog/log-export/org/storage-export/README.md
  catalog/log-export/org/storage-export/export.yaml
  catalog/log-export/org/storage-export/setters.yaml
Labels: approved, size/M

#187 fix!: replace bucket policy in storage log export with uniform bucket level access
  catalog/log-export/folder/storage-export/README.md
  catalog/log-export/folder/storage-export/export.yaml
  catalog/log-export/folder/storage-export/setters.yaml
  catalog/log-export/org/storage-export/README.md
  catalog/log-export/org/storage-export/export.yaml
  catalog/log-export/org/storage-export/setters.yaml
Labels: lgtm, approved, size/M

#177 feat: gitops multirepo update
  catalog/gitops/configsync/README.md
  catalog/gitops/configsync/config-management.yaml
  catalog/gitops/configsync/configsync-iam.yaml
  catalog/gitops/configsync/rootsync.yaml
Labels: approved, size/M

#184 feat: add blueprint for cloud sql auth proxy
  .gitignore
  .release-please-manifest.json
  catalog/sql/auth-proxy/Kptfile
  catalog/sql/auth-proxy/README.md
  catalog/sql/auth-proxy/daemonset.yml
  catalog/sql/auth-proxy/service.yml
  catalog/sql/auth-proxy/serviceAccount.yml
  catalog/sql/auth-proxy/setters.yaml
  release-please-config.json
Labels: approved, size/L, needs-ok-to-test
