Repository GoogleCloudPlatform/blueprints, pull requests merged in 2022-03, with the labels that each got.

#164 Add 'ignore-clusterless' annotations to resources that are irrelevant to clusterless actuation.
  catalog/landing-zone/namespaces/hierarchy.yaml
  catalog/landing-zone/namespaces/logging.yaml
  catalog/landing-zone/namespaces/networking.yaml
  catalog/landing-zone/namespaces/policies.yaml
  catalog/landing-zone/namespaces/projects.yaml
  catalog/project/kcc-namespace/kcc.yaml
Labels: size/XS, lgtm, ok-to-test

#168 update hierarchy blueprint to use set-namespace instead of apply-setter
  catalog/hierarchy/bu/Kptfile
  catalog/hierarchy/bu/README.md
  catalog/hierarchy/bu/hierarchy.yaml
  catalog/hierarchy/bu/setters.yaml
  catalog/hierarchy/env-bu/Kptfile
  catalog/hierarchy/env-bu/README.md
  catalog/hierarchy/env-bu/hierarchy.yaml
  catalog/hierarchy/env-bu/setters.yaml
  catalog/hierarchy/env-bu/shared-folders.yaml
  catalog/hierarchy/simple/Kptfile
  catalog/hierarchy/simple/README.md
  catalog/hierarchy/simple/hierarchy.yaml
  catalog/hierarchy/simple/setters.yaml
  catalog/hierarchy/team/Kptfile
  catalog/hierarchy/team/README.md
  catalog/hierarchy/team/hierarchy.yaml
  catalog/hierarchy/team/setters.yaml
Labels: approved, size/L, ok-to-test

#169 Add project name as a separate field to allow for setting of the name independent of ID
  catalog/project/README.md
  catalog/project/project.yaml
  catalog/project/setters.yaml
Labels: size/XS, ok-to-test

#171 Set separate project & networking namespaces
  catalog/networking/svpc-service-project/README.md
  catalog/networking/svpc-service-project/serviceproject.yaml
  catalog/networking/svpc-service-project/setters.yaml
Labels: size/S, lgtm, approved

#170 fix: ignore namespace IAM resources in clusterless mode
  catalog/landing-zone/namespaces/hierarchy.yaml
  catalog/landing-zone/namespaces/logging.yaml
  catalog/landing-zone/namespaces/networking.yaml
  catalog/landing-zone/namespaces/policies.yaml
  catalog/landing-zone/namespaces/projects.yaml
Labels: lgtm, approved, size/M

#179 fix: remove gitops ConfigManagement syncRevision field
  catalog/gitops/configsync/config-management.yaml
Labels: size/XS, lgtm, approved
