Repository GoogleCloudPlatform/blueprints, pull requests merged in 2023-02, with the labels that each got.

#204 fix: update generate-kpt-pkg-docs version to fix bug
  catalog/acm/README.md
  catalog/anthos-cluster/README.md
  catalog/bucket/README.md
  catalog/empty/README.md
  catalog/gitops/README.md
  catalog/gitops/configsync/README.md
  catalog/gke-autopilot/README.md
  catalog/gke/README.md
  catalog/gke/cluster/README.md
  catalog/gke/nodepools/primary/README.md
  catalog/hierarchy/bu/README.md
  catalog/hierarchy/env-bu/README.md
  catalog/hierarchy/simple/README.md
  catalog/hierarchy/team/README.md
  catalog/iam-foundation/README.md
  catalog/landing-zone-lite/README.md
  catalog/landing-zone/README.md
  catalog/log-export/folder/bigquery-export/README.md
  catalog/log-export/folder/logbucket-export/README.md
  catalog/log-export/folder/pubsub-export/README.md
  catalog/log-export/folder/storage-export/README.md
  catalog/log-export/org/bigquery-export/README.md
  catalog/log-export/org/logbucket-export/README.md
  catalog/log-export/org/pubsub-export/README.md
  catalog/log-export/org/storage-export/README.md
  catalog/networking/dns/managedzone-forwarding/README.md
  catalog/networking/dns/managedzone-peering/README.md
  catalog/networking/dns/managedzone-private/README.md
  catalog/networking/dns/policy/README.md
  catalog/networking/dns/recordset/README.md
  catalog/networking/firewall/common-rules/README.md
  catalog/networking/network/README.md
  catalog/networking/network/subnet/README.md
  catalog/networking/network/vpc/README.md
  catalog/networking/peering/README.md
  catalog/networking/routes/routes-igw/README.md
  catalog/networking/shared-vpc/README.md
  catalog/networking/svpc-service-project/README.md
  catalog/networking/vpc-service-controls/access-policy/README.md
  catalog/networking/vpc-service-controls/perimeter/README.md
  catalog/project/README.md
  catalog/project/kcc-namespace/README.md
  catalog/redis-bucket/README.md
  catalog/spanner/README.md
  catalog/sql/auth-proxy/README.md
  utils/lint.sh
Labels: approved, size/M, ok-to-test

#209 chore: remove --include-meta-resources
  utils/lint.sh
Labels: size/XS, lgtm, approved

#210 chore: update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, approved

#197 fix: reduce setters for ACM on GKE blueprint
  catalog/anthos-cluster/acm/README.md
  catalog/anthos-cluster/acm/config-mgmt-csr.yaml
  catalog/anthos-cluster/acm/setters.yaml
Labels: size/XS, approved

#211 chore: update lint and conventional-commit
  .github/conventional-commit-lint.yaml
  .github/workflows/schema.yml
Labels: size/S, approved

#203 feat: add iam cnrm resources to sql auth proxy
  CONTRIBUTING.md
  catalog/sql/auth-proxy/Kptfile
  catalog/sql/auth-proxy/README.md
  catalog/sql/auth-proxy/daemonset.yaml
  catalog/sql/auth-proxy/iam.yaml
  catalog/sql/auth-proxy/service.yaml
  catalog/sql/auth-proxy/serviceAccount.yaml
  catalog/sql/auth-proxy/setters.yaml
Labels: lgtm, approved, size/L, ok-to-test

#207 chore: add stale.yml
  .github/workflows/stale.yml
Labels: size/S, lgtm, approved

#212 feat: cloud-sql-proxy 2.0.0 and metrics support
  catalog/sql/auth-proxy/README.md
  catalog/sql/auth-proxy/daemonset.yaml
  catalog/sql/auth-proxy/iam.yaml
Labels: size/S, lgtm, approved, ok-to-test
